### ISSUE TITLE
Investigate node version warning

### ISSUE THREAD

**Issue by gcapes** [gcapes/rocrate-to-ghpages-action#3]
As given here: https://github.com/gcapes/remote-test-rocratebuild/actions/runs/3250941436

[Blog post](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

**Comment by stain** [comment]
Might be fixed in https://www.npmjs.com/package/ro-crate-html -- note rename in npm!

**Comment by gcapes** [comment]
Also consider loading nodejs using an action instead of in the docker container.

**Comment by gcapes** [comment]
I've not had much luck installing `npm install ro-crate-html`.
It didn't install to `./node_modules` like I was expecting, but appears to have instead installed to `~/node_modules/`
Anyway, when I try to use it it doesn't work
```
remote-test-rocratebuild (master %=) $ ~/node_modules/.bin/rochtml ro-crate-metadata.json 
/home/mbexegc2/node_modules/ro-crate-html/node_modules/ro-crate/lib/rocrate.js:39
  static defaults = defaults;
                  ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/mbexegc2/node_modules/ro-crate-html/node_modules/ro-crate/index.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```
This is definitely the newly installed package I'm using
```
remote-test-rocratebuild (master %=) $ ls -lh ~/node_modules/.bin/rochtml 
lrwxrwxrwx 1 mbexegc2 mbexegc2 28 Oct 28 09:27 /home/mbexegc2/node_modules/.bin/rochtml -> ../ro-crate-html/roc-html.js
```

The old one `ro-crate-html-js` works fine
```
remote-test-rocratebuild (master %=) $ ~/projects/esciencelab/rocrate-to-pages/node_modules/.bin/rochtml ro-crate-metadata.json 
remote-test-rocratebuild (master %=) $ ls
ro-crate-metadata.json  ro-crate-preview.html
```
So I'm going to stick with that for now, and investigate loading nodejs using an action.

**Comment by gcapes** [comment]
It seems that I don't need to write a separate action for this at all. I've done it all in a [workflow](https://github.com/gcapes/remote-test-rocratebuild/blob/workflow-only/.github/workflows/rocrate_to_pages.yml). However, I still have the node version warning, which I think is because the pages-build-and-deployment action uses actions/checkout@v2 instead of actions/checkout@v3. So there's nothing I can do about that.

**Comment by stain** [comment]
You can install with `npm install -g` to add to the global NPM install, perhaps make sure it's in a fresh Node environment so you don't get the old dependencies or something. The bug with `=` I can reproduce

```
(ro-crate) stain@xena11:~$ rochtml
/home/stain/miniconda3/envs/ro-crate/lib/node_modules/ro-crate-html/node_modules/ro-crate/lib/rocrate.js:39
  static defaults = defaults;
                  ^

SyntaxError: Unexpected token =
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
```
